"""HLK/chain/__init__.py - Lazy re-export of verify-first chain.

PEP 562 lazy import: only load module when user references symbol.
Backward compat: all old symbols still accessible by same name.
"""
from __future__ import annotations
import importlib
from typing import Any

_LAZY_MODULES: dict[str, str] = {
    "AUDIT_LOG_PATH": "auto_pr_runner",
    "Actor": "brd_schema",
    "AgentCall": "redteam_spawner",
    "AggregateResult": "redteam_spawner",
    "AgreementPolicy": "judge_config",
    "AuditConfig": "judge_config",
    "BRD": "brd_schema",
    "BenchResult": "skill_bench",
    "BinaryCheck": "rubric_generator",
    "BinaryRubric": "rubric_generator",
    "BrowserStepResult": "agent_browser_runner",
    "CCConfig": "command_code_client",
    "CCResponse": "command_code_client",
    "CIRCUIT_BREAKER_COOLDOWN_SECONDS": "command_code_client",
    "DEFAULT_BASE": "auto_pr_gh",
    "DEFAULT_CC_BIN": "agent_browser_runner",
    "DEFAULT_CIRCUIT_BREAKER_THRESHOLD": "command_code_client",
    "DEFAULT_CONFIG_PATH": "auto_pr_runner",
    "DEFAULT_GH_BIN": "auto_pr_gh",
    "DEFAULT_MAX_RETRIES": "command_code_client",
    "DEFAULT_PARALLEL": "skill_bench",
    "DEFAULT_SCENARIOS_PER_SKILL": "skill_bench",
    "DEFAULT_TIMEOUT": "agent_browser_runner",
    "EnvHandle": "verify_env_setup",
    "Evidence": "scenario_runner",
    "FailureObservation": "skill_promoter",
    "Finding": "secret_scanner",
    "FunctionalRequirement": "brd_schema",
    "GHResult": "auto_pr_gh",
    "GateCheck": "auto_pr_runner",
    "GateResult": "auto_pr_runner",
    "GateVerdict": "auto_pr_runner",
    "GeneratedTest": "test_generator",
    "JudgeConfig": "judge_config",
    "KILL_SWITCH_PATH": "auto_pr_runner",
    "MAX_DRAFTS_PER_RUN": "skill_promoter",
    "MAX_PROMPT_LENGTH": "prompt_sanitizer",
    "MIN_EXECUTORS": "skill_promoter",
    "MIN_FAIL_RATE": "skill_promoter",
    "MIN_OCCURRENCES": "skill_promoter",
    "NonFunctionalRequirement": "brd_schema",
    "RedteamConfig": "judge_config",
    "RedteamRound": "redteam_spawner",
    "Scenario": "scenario_runner",
    "ScenarioResult": "scenario_runner",
    "ScoreRubric": "rubric_generator",
    "SkillDraft": "skill_promoter",
    "Step": "scenario_runner",
    "StepResult": "scenario_runner",
    "StepStatus": "scenario_runner",
    "VerifyEnv": "verify_env_setup",
    "aggregate_verdicts": "redteam_spawner",
    "bench_skills": "skill_bench",
    "boot_env": "verify_env_setup",
    "boot_env_from_yaml": "verify_env_setup",
    "build_redteam_round": "redteam_spawner",
    "capture_screenshot": "agent_browser_runner",
    "chat": "command_code_client",
    "check_adversarial_consensus": "auto_pr_runner",
    "check_auth_status": "auto_pr_gh",
    "check_ci": "auto_pr_gh",
    "check_coverage_matrix": "auto_pr_runner",
    "check_fable_judge": "auto_pr_runner",
    "check_gh_installed": "auto_pr_gh",
    "check_llm_judge_rubric": "auto_pr_runner",
    "check_rate_limit": "auto_pr_runner",
    "check_repo": "auto_pr_gh",
    "create_pr": "auto_pr_gh",
    "ensure_utf8_output": "_platform_utils",
    "find_promotion_candidates": "skill_promoter",
    "generate_binary_test": "test_generator",
    "generate_from_rubric_file": "test_generator",
    "generate_rubric_file": "rubric_generator",
    "generate_rubrics": "rubric_generator",
    "generate_score_test": "test_generator",
    "get_judge_model": "judge_config",
    "get_python_cmd": "_platform_utils",
    "get_verify_first_config": "config",
    "has_secret": "secret_scanner",
    "is_hlk_config_complete": "config",
    "is_kill_switch_active": "auto_pr_runner",
    "is_linux": "_platform_utils",
    "is_macos": "_platform_utils",
    "is_posix": "_platform_utils",
    "is_safe": "prompt_sanitizer",
    "is_windows": "_platform_utils",
    "live_auto_merge": "auto_pr_gh",
    "load_config": "auto_pr_runner",
    "load_hlk_config": "config",
    "load_judge_config": "judge_config",
    "make_executable": "_platform_utils",
    "make_scenarios_from_brd": "scenario_runner",
    "merge_pr": "auto_pr_gh",
    "normalize_path": "_platform_utils",
    "parallel_chat": "command_code_client",
    "parse_brd_file": "brd_validator",
    "parse_brd_text": "brd_validator",
    "pick_cross_model": "command_code_client",
    "pick_judge_for_audit_path": "judge_config",
    "preflight": "auto_pr_gh",
    "redact": "secret_scanner",
    "render_bench_report": "skill_bench",
    "render_skill_markdown": "skill_promoter",
    "reset_circuit_breaker": "command_code_client",
    "rotate_audit_log": "auto_pr_runner",
    "run_browser_step": "agent_browser_runner",
    "run_gates": "auto_pr_runner",
    "run_python": "_platform_utils",
    "run_redteam_round": "redteam_spawner",
    "run_scenario": "scenario_runner",
    "safe_chmod": "_platform_utils",
    "sanitize": "prompt_sanitizer",
    "scan": "secret_scanner",
    "scan_diff_for_secrets": "auto_pr_gh",
    "scan_summary": "secret_scanner",
    "should_auto_merge": "auto_pr_runner",
    "should_spawn_redteam": "judge_config",
    "validate_brd_dict": "brd_schema",
    "wait_for_ci": "auto_pr_gh",
    "write_audit_log": "auto_pr_runner",
    "write_drafts_to_queue": "skill_promoter",
}

__all__ = sorted(_LAZY_MODULES.keys())

def __getattr__(name: str) -> Any:
    """PEP 562 lazy import - only load module when symbol accessed."""
    if name in _LAZY_MODULES:
        module = importlib.import_module("HLK.chain." + _LAZY_MODULES[name])
        value = getattr(module, name)
        globals()[name] = value
        return value
    raise AttributeError("module HLK.chain has no attribute " + repr(name))

def __dir__() -> list[str]:
    """Return all public symbols (for dir() support)."""
    return list(__all__)

