#!/usr/bin/env python3
"""loop_memory_fallback.py — U06 Fallback mechanism for Memory Keeper single-point-of-failure.

This module provides fallback registry writing when primary write fails.
"""
from __future__ import annotations

import json
import sys
import traceback
from datetime import datetime, timezone
from pathlib import Path

try:
    import ahd_session
except ImportError:  # pragma: no cover
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "hooks"))
    import ahd_session

# Constants (duplicated from loop_memory_sync for standalone operation)
MAX_ACTIVE_SESSIONS = 3
ACTIVE_STATUSES = ("in_progress", "crashed", "suspected_crashed")

# U06: Fallback paths for Memory Keeper single-point-of-failure
FALLBACK_DIR_NAME = "loop_state_fallback"
FALLBACK_REGISTRY_NAME = "loop_state_fallback.md"


def _write_fallback(root: Path, operation: str, error: str) -> None:
    """U06: Write fallback registry when primary write fails.

    If loop_memory_sync fails to write the main registry, this function
    writes a minimal fallback to loop_state_fallback.md so the harness
    can still recover session state.
    """
    try:
        fallback_dir = ahd_session.get_config_root(root) / FALLBACK_DIR_NAME
        fallback_dir.mkdir(parents=True, exist_ok=True)

        # Write individual session snapshots from session_state
        session_dir = ahd_session.get_config_root(root) / "session_state"
        if session_dir.exists():
            for f in session_dir.glob("*.json"):
                try:
                    data = json.loads(f.read_text(encoding="utf-8"))
                    sid = data.get("session_id", f.stem)
                    snap = {
                        "session_id": sid,
                        "status": data.get("status", "unknown"),
                        "goal": data.get("goal", ""),
                        "last_heartbeat": data.get("last_heartbeat", ""),
                        "last_state_write": data.get("last_state_write", ""),
                        "tags": data.get("tags", []),
                        "owned_files": data.get("owned_files", []),
                    }
                    snap_path = fallback_dir / f"{sid}.json"
                    snap_path.write_text(json.dumps(snap, ensure_ascii=False, indent=2), encoding="utf-8")
                except (json.JSONDecodeError, TypeError, ValueError, OSError, UnicodeDecodeError):
                    pass

        # Write fallback registry
        fallback_reg = fallback_dir.parent / FALLBACK_REGISTRY_NAME
        ts = datetime.now(timezone.utc).isoformat()
        lines = [
            "---",
            f"fallback: true",
            f"generated: {ts}",
            f"reason: {operation} failed",
            "---",
            "",
            "# Loop State Registry (FALLBACK)",
            "",
            f"> Primary registry write failed at {ts}.",
            f"> Error: {error[:200]}",
            f"> This fallback was generated by loop_memory_sync.py U06 fallback mechanism.",
            "",
            "## Session snapshots",
            "| session_id | status | goal | last_heartbeat |",
            "|---|---|---|---|",
        ]
        if fallback_dir.exists():
            for snap_file in sorted(fallback_dir.glob("*.json")):
                try:
                    snap = json.loads(snap_file.read_text(encoding="utf-8"))
                    sid = snap.get("session_id", snap_file.stem)
                    status = snap.get("status", "unknown")
                    goal = snap.get("goal", "")[:30]
                    hb = snap.get("last_heartbeat", "")
                    lines.append(f"| {sid} | {status} | {goal} | {hb} |")
                except (json.JSONDecodeError, TypeError, ValueError, OSError, UnicodeDecodeError):
                    pass
        lines.append("")
        lines.append(f"## Recovery instructions")
        lines.append(f"- Check error: {error[:200]}")
        lines.append(f"- Individual session snapshots in .devin/{FALLBACK_DIR_NAME}/")
        lines.append(f"- Fix primary write issue, then re-run loop_memory_sync.py")
        lines.append(f"- Fallback snapshots can be merged back manually if needed")

        fallback_reg.write_text("\n".join(lines) + "\n", encoding="utf-8")
    except (json.JSONDecodeError, TypeError, ValueError) as e:
        # Last resort: can't even write fallback
        print(f"[loop_memory_sync] fallback write failed: {e}", file=sys.stderr)
        pass

    except Exception as e:
        # Last resort: can't even write fallback
        print(f"[loop_memory_sync] fallback write failed: {e}", file=sys.stderr)
        pass


def _safe_regenerate(root: Path, session_id: str = "", status: str = "") -> None:
    """U06: Wrapper around regenerate() with fallback on failure."""
    try:
        # Import here to avoid circular import and pick up monkeypatched version
        from loop_memory_sync import regenerate  # type: ignore[import-not-found]
        regenerate(root, session_id, status)
    except Exception as e:
        tb = traceback.format_exc()
        _write_fallback(root, "regenerate", f"{e}: {tb[:500]}")
        # Re-raise so caller knows it failed, but fallback is written
        raise