modelRoleStorage: project
enabledModels:
  - commandcode/poolside/laguna-s-2.1-free
  - commandcode/deepseek/deepseek-v4-flash-fast
  - commandcode/z-ai/glm-5.3-flash
  - commandcode/google/gemini-3.8-flash
  - commandcode/meta/muse-spark-1.3
  - commandcode/claude-fable-5-1
  - commandcode/meituan/LongCat-2.0:free
  - opencode-go/ox-alpha-free
  - opencode-go/hy3-preview
  - opencode-zen/deepseek-v4-flash-free
  - opencode-zen/laguna-s-2.1-free
  - opencode-zen/minimax-m2.5-free
  - opencode-zen/minimax-m3-free
  - opencode-zen/qwen3.6-plus-free
  - opencode-zen/mimo-v2.5-free
  - opencode-zen/nemotron-3-ultra-free
  - opencode-zen/nemotron-3.5-lightning-free
  - opencode-zen/x-preview-f-free
  - google-antigravity/gpt-oss-120b
  - google-antigravity/gemini-3.1-flash-image
  - devin/swe-1-6-slow
modelRoles:
  default: null
  plan: commandcode/poolside/laguna-s-2.1-free
  slow: commandcode/z-ai/glm-5.3-flash
  task: commandcode/poolside/laguna-s-2.1-free
  advisor: commandcode/poolside/laguna-s-2.1-free
  designer: commandcode/poolside/laguna-s-2.1-free
  smol: opencode-go/ox-alpha-free:auto
  tiny: opencode-go/ox-alpha-free
  commit: commandcode/z-ai/glm-5.3-flash