#!/usr/bin/env python3
# tools/gen_source_map.py
# Sinh `.clinerules/00-source-map.md` — bản đồ source nén, Cline tự nạp đầu mỗi session.
# Nguồn cây file: `git ls-files` (tracked) — chính xác, bỏ qua runtime/ignored.
# Chạy lại khi cấu trúc workspace thay đổi: `python3 tools/gen_source_map.py`

from __future__ import annotations

import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / ".clinerules" / "00-source-map.md"

sys.path.insert(0, str(ROOT / "tools"))
import source_map_data as D  # noqa: E402

TOP_LEVEL_ORDER = [
    ".devin", "tests", ".opencode", "HLK", ".github", "docs",
    "tools", "specs", "sbom",
]

TEST_CANDIDATES = [
    ".devin/scripts/{n}",
    ".devin/scripts/plan_fsm/{n}",
    ".devin/scripts/runtime/{n}",
    ".devin/scripts/graph_engine/{n}",
    ".devin/scripts/state_store/{n}",
    ".devin/scripts/adapters/{n}",
    ".devin/scripts/state_machine_v2/{n}",
    ".devin/scripts/agents/{n}",
    ".devin/hooks/{n}",
    "tools/{n}",
]


def tracked_files() -> list[str]:
    try:
        out = subprocess.run(
            ["git", "-C", str(ROOT), "ls-files"],
            capture_output=True, text=True, timeout=15, check=False,
        )
        if out.returncode == 0 and out.stdout.strip():
            return sorted(p for p in out.stdout.splitlines() if p.strip())
    except Exception:
        pass
    sys.stderr.write("WARN: git ls-files fail — dùng os.walk fallback\n")
    skip_dirs = {
        ".git", "node_modules", ".venv", "dist", "build", "__pycache__",
        ".pytest_cache", ".omo", ".codegraph", ".khuym", ".aide", ".clinerules",
        ".devin/loop_state", ".devin/session_state", ".devin/plan_state",
        ".devin/context_flags", ".devin/blackboard", ".devin/event_bus",
        ".devin/state", ".devin/telemetry", ".devin/artifacts",
        ".devin/agents_state", ".devin/loop_state_archive",
        ".devin/idempotency", ".devin/checkpoints", ".devin/artifact_registry",
        ".worktrees",
    }
    import os
    result = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        rel = Path(dirpath).relative_to(ROOT)
        dirnames[:] = [d for d in dirnames if str(rel / d) not in skip_dirs]
        for f in sorted(filenames):
            if f in ("package-lock.json", ".DS_Store"):
                continue
            result.append(str(rel / f) if str(rel) != "." else f)
    return sorted(result)


def md_table(header: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(header) + " |",
             "|" + "---|" * len(header)]
    for r in rows:
        lines.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(lines)

def main() -> int:
    files = tracked_files()
    fset = set(files)

    out: list[str] = []
    out.append("# Source Map — Workspace AHD (Cline Index)")
    out.append("<!-- generated by tools/gen_source_map.py — DO NOT EDIT -->")
    out.append("")
    out.append("> Bản đồ toàn bộ source (tracked files), nạp tự động đầu mỗi session.")
    out.append("> Refresh khi cấu trúc thay đổi: `python3 tools/gen_source_map.py`")
    out.append("> Deep-dive: `STRUCTURAL_COMPONENT_MAP.md`, `ITERATION_4_COMPONENT_MAP.md`.")
    out.append("")

    out.append("## 1. Tổng quan")
    out.append("")
    out.append(f"Tổng cộng **{len(files)}** tracked files. Layer chính:")
    out.append("")
    rows = []
    for d in TOP_LEVEL_ORDER:
        n = sum(1 for f in files if f.startswith(d + "/"))
        rows.append([f"`{d}/`", str(n), D.DIR_NOTES.get(d, "")])
    rows.append(["`<root>/`", str(sum(1 for f in files if "/" not in f)),
                 "File gốc — xem mục 2"])
    out.append(md_table(["Thư mục", "Files", "Vai trò"], rows))
    out.append("")

    root_files = sorted(f for f in files if "/" not in f)
    out.append("## 2. File root")
    out.append("")
    rows = []
    for f in root_files:
        desc = D.ROOT_NOTES.get(f, "")
        if not desc and f.endswith(("_REPORT.md", "_ANALYSIS.md", "_PLAN.md",
                                    "_MATRIX.md", "_AUDIT.md")):
            desc = "Báo cáo/plan (lịch sử — đọc khi cần)"
        rows.append([f"`{f}`", desc])
    out.append(md_table(["File", "Vai trò"], rows))
    out.append("")

    out.append("## 3. `.devin/` — AHD engine")
    out.append("")

    devin_root = sorted(f.split("/", 1)[1] for f in files
                        if f.startswith(".devin/") and f.count("/") == 1)
    out.append("### 3.1 Entry + config `.devin/`")
    out.append("")
    rows = [[f"`{b}`", D.DEVIN_ROOT_NOTES.get(b, "")] for b in devin_root]
    out.append(md_table(["File", "Vai trò"], rows))
    out.append("")

    canon = sorted(f.split("/")[-1] for f in files
                   if f.startswith(".devin/canon/") and f.endswith(".md"))
    out.append("### 3.2 canon/ — protocol files")
    out.append("")
    rows = [[f"`{c}`", D.CANON_NOTES.get(c, "")] for c in canon]
    out.append(md_table(["File", "Vai trò"], rows))
    out.append("")

    skill_dirs = sorted(d for d in D.SKILL_NOTES if not d.endswith(".md"))
    skill_flat = sorted(d for d in D.SKILL_NOTES if d.endswith(".md"))
    out.append("### 3.3 skills/ — packages + flat files")
    out.append("")
    out.append("- **Skill packages:**")
    for s in skill_dirs:
        out.append(f"  - `{s}` — {D.SKILL_NOTES[s]}")
    out.append("- **Flat skill files:**")
    for s in skill_flat:
        out.append(f"  - `{s}` — {D.SKILL_NOTES[s]}")
    out.append("")
    out.append("- `skill_index.json` — chỉ mục skills (2KB, nạp boot).")
    out.append("")

    agents = sorted(f.split(".devin/agents/")[1] for f in files
                    if f.startswith(".devin/agents/"))
    out.append("### 3.4 agents/")
    out.append("")
    rows = [[f"`{a}`", D.AGENT_NOTES.get(a, "")] for a in agents]
    out.append(md_table(["File", "Vai trò"], rows))
    out.append("")

    hooks = sorted(f.split("/")[-1] for f in files
                   if f.startswith(".devin/hooks/") and f.endswith(".py"))
    out.append("### 3.5 hooks/ — 17 Python hook guards")
    out.append("")
    rows = [[f"`{h}`", D.HOOK_NOTES.get(h, "")] for h in hooks]
    out.append(md_table(["File", "Vai trò"], rows))
    out.append("")

    scripts = [f.split("/")[-1] for f in files
               if f.startswith(".devin/scripts/") and f.endswith(".py")
               and "/" not in f.split(".devin/scripts/")[1]]
    script_set = set(scripts)
    grouped = defaultdict(list)
    for gname, names in D.SCRIPT_GROUPS.items():
        for n in names:
            if n in script_set:
                grouped[gname].append(n)
                script_set.remove(n)
    out.append("### 3.6 scripts/ — Python runtime scripts")
    out.append("")
    for gname in list(D.SCRIPT_GROUPS.keys()) + ["Khác (chưa phân nhóm)"]:
        items = grouped.get(gname, [])
        if gname == "Khác (chưa phân nhóm)":
            items = sorted(script_set)
        if not items:
            continue
        out.append(f"**{gname}:**")
        for f in sorted(items):
            out.append(f"- `{f}` — {D.SCRIPT_NOTES.get(f, '')}")
        out.append("")
    subpkg = sorted(f.split(".devin/scripts/")[1] for f in files
                    if f.startswith(".devin/scripts/") and f.endswith(".py")
                    and "/" in f.split(".devin/scripts/")[1]
                    and f.split(".devin/scripts/")[1].count("/") >= 1)
    out.append("**Subpackages (`.devin/scripts/<pkg>/`):**")
    for f in subpkg:
        out.append(f"- `{f}` — {D.SUBPACKAGE_NOTES.get(f, '')}")
    out.append("")

    out.append("## 4. `.opencode/` — wrapper layer")
    out.append("")
    rows = []
    for f in sorted(D.OPCODE_NOTES):
        if (".opencode/" + f) in fset:
            rows.append([f"`{f}`", D.OPCODE_NOTES[f]])
    rows.append(["`agent/*.md`", "15 agent wrappers → nạp file gốc `.devin/agents/`"])
    rows.append(["`skills/`", "skill wrappers → nạp file gốc `.devin/skills/`"])
    rows.append(["`tools/*.sh`", "11 harness bash tools (consensus, verify, compact, mask, ...)"])
    rows.append(["`hooks/*.sh`", "5 shell hook bridges (fail-open)"])
    out.append(md_table(["File", "Vai trò"], rows))
    out.append("")

    out.append("## 5. `HLK/` — security layer (KHÔNG đụng)")
    out.append("")
    rows = []
    for f in sorted(D.HLK_NOTES):
        if ("HLK/" + f) in fset:
            rows.append([f"`{f}`", D.HLK_NOTES[f]])
    rows.append(["`bin/*.mjs`", "CLI lifecycle (install, update, pack, repack, status)"])
    rows.append(["`docs/`", "17 tài liệu HLK tiếng Việt"])
    rows.append(["`reports/`", "analysis reports + learnings"])
    rows.append(["`setup/`", "install scripts (sh/ps1/mjs)"])
    out.append(md_table(["File", "Vai trò"], rows))
    out.append("")

    out.append("## 6. tests/ — pytest files (coverage gate 80%)")
    out.append("")
    out.append("- `conftest.py` — fixtures + paths (`.devin/scripts`, `.devin/hooks`)")
    test_files = sorted(f.split("/")[-1] for f in files
                        if f.startswith("tests/") and f.endswith(".py")
                        and f != "tests/conftest.py")
    test_map = defaultdict(list)
    for t in test_files:
        test_map[resolve_test_target(t, fset)].append(t)
    for target in sorted(test_map):
        names = ", ".join(f"`{t}`" for t in test_map[target])
        out.append(f"- {names} — → {target}")

    out.append("## 7. docs/")
    out.append("")
    rows = []
    for f in sorted(D.DOC_NOTES):
        if (ROOT / "docs" / f).exists():
            rows.append([f"`docs/{f}`", D.DOC_NOTES[f]])
    rows.append(["`plans/`", "plan artifacts theo feature (ví dụ source-audit-fix)"])
    rows.append(["`reports/`", "quality/security reports"])
    rows.append(["`research/`", "research notes (orchestration, planning, QC)"])
    out.append(md_table(["File", "Vai trò"], rows))
    out.append("")

    out.append("## 8. tools/")
    out.append("")
    rows = [[f"`{f}`", D.TOOL_NOTES[f]] for f in sorted(D.TOOL_NOTES)]
    out.append(md_table(["File", "Vai trò"], rows))
    out.append("")

    out.append("## 9. `.github/` — CI/CD + supply-chain")
    out.append("")
    rows = []
    for f in sorted(D.GITHUB_NOTES):
        if f in ("CODEOWNERS", "dependabot.yml"):
            if (".github/" + f) in fset:
                rows.append([f"`{f}`", D.GITHUB_NOTES[f]])
        elif (".github/" + f) in fset:
            rows.append([f"`{f}`", D.GITHUB_NOTES[f]])
    rows.append(["`workflows/*.yml` (khác)", "37 workflows: ci, v3-ci, integration, verification, codeql, supply-chain, smoke tests, ..."])
    out.append(md_table(["File", "Vai trò"], rows))
    out.append("")

    out.append("## 10. specs/ + sbom/")
    out.append("")
    out.append("- `specs/plan_orchestrator.tla`, `specs/state_router.tla` — TLA+ formal specs")
    out.append("- `sbom/npm.sbom.json`, `sbom/python.sbom.json` — Software Bill of Materials")
    out.append("")

    out.append("## 11. Runtime / ignored — KHÔNG đọc")
    out.append("")
    out.append("- `.devin/loop_state/`, `session_state/`, `plan_state/`, `context_flags/`, `blackboard/`, `event_bus/`, `telemetry/`, `state/`, `artifacts/`, `checkpoints/`, `idempotency/`, `agent_state/` — state runtime (gitignored)")
    out.append("- `.omo/`, `.codegraph/`, `.khuym/`, `.aide/` — runtime/config plugin (không phải source)")
    out.append("- `node_modules/`, `.venv/`, `dist/`, `build/` — dependencies/build")
    out.append("- `HARNESS_UPGRADE_REPORT.md`, `harness-upgrade-log.md`, `EXECUTION_*.md`, `MIGRATION_*.md`, `STRUCTURAL_*.md`, `SECURITY_*.md`, `ARCHITECTURAL_ATTACK_REPORT.md` — báo cáo lịch sử, chỉ đọc khi cần context quá khứ")
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(out) + "\n"
    OUT.write_text(body, encoding="utf-8")
    print(f"OK: {OUT} — {len(out)} lines, {len(body)} chars, {len(files)} files")
    return 0


def resolve_test_target(test_file: str, fset: set[str]) -> str:
    base = test_file[:-3]
    if base.startswith("test_"):
        base = base[len("test_"):]
    for pattern in TEST_CANDIDATES:
        if pattern.format(n=base + ".py") in fset:
            return pattern.format(n=base + ".py")
    best = None
    for cand_file in fset:
        if cand_file == "tests/" + test_file or not cand_file.endswith(".py"):
            continue
        name = cand_file.rsplit("/", 1)[-1][:-3]
        if base.startswith(name) and name:
            if best is None or len(name) > len(best[0]):
                best = (name, cand_file)
    if best:
        return best[1]
    return "(integration/harness test)"


if __name__ == "__main__":
    raise SystemExit(main())

