# tools/source_map_data.py
# Dữ liệu mô tả rút gọn cho source map (`tools/gen_source_map.py`).
# Sửa file này khi cần cập nhật mô tả; cây file tự sinh từ `git ls-files`.

# Mô tả thư mục cấp cao + phân hệ (key = path tương đối từ root).
DIR_NOTES = {
    ".devin": "AHD engine — canon, skills, agents, hooks, scripts (động cơ chính của workspace)",
    ".clinerules": "Cline rules layer — auto-load mỗi session (source map + orientation + protocols + governance)",
    ".devin/rules": "project rules layer (project-owned) — WORKSPACE_GOVERNANCE.md (canonical file/folder governance)",
    ".devin/canon": "15 protocol files — rule gốc tool-agnostic (CORE_CANON, BOOT_PROTOCOL, REDLINES, ...)",
    ".devin/skills": "14 skill packages + 17 flat skill files + skill_index.json (chỉ mục)",
    ".devin/agents": "COMMANDER + 5 workers + 6 personas + 3 executors + templates",
    ".devin/hooks": "17 Python hook guards (pre/post tool, session, plan_enforce, schema_gate, ...)",
    ".devin/scripts": "64 Python runtime scripts (orchestrator, FSM, state, memory, quality, cost, ...)",
    ".devin/schemas": "JSON schema cho hook IO (hook_io_schema_v1.json)",
    ".devin/metadata": "patch/review reports + REPOS_TRACKER.json",
    ".devin/prompts": "prompt cho microscopic review",
    ".devin/reports": "QA audit + source audit reports",
        ".devin/rules": "project rules layer (project-owned) — WORKSPACE_GOVERNANCE.md (canonical file/folder governance)",
    ".devin/upgrade": "upgrade execution protocol + upgrade trackers",
    ".devin/loop_state.md": "registry loop state (tracked) — đọc ở boot",
    ".devin/loop_state_archive.md": "archive loop state",
    ".opencode": "opencode wrapper layer — tái sử dụng skills/agents/hooks của harness (không đụng .devin)",
    ".opencode/agent": "15 agent wrappers (commander, scout, verifier, saboteur, ...) → trỏ về .devin/agents",
    ".opencode/agents": "5 harness agents (orchestrator, 3 executors, subagent, verifier)",
    ".opencode/skills": "skill wrappers → trỏ agent nạp file gốc .devin/skills",
    ".opencode/tools": "11 harness bash tools (route, consensus, compress, mask, compact, bestofn, cost, fable)",
    ".opencode/hooks": "5 shell hook bridges (fail-open)",
    ".opencode/command": "/harness-upgrade command launcher",
    ".opencode/plugin": "harness.ts — hook bridge (opt-in, mặc định tắt)",
    "HLK": "Harness & Logic Knowledge — security layer (Node) — KHÔNG đụng",
    "HLK/wrappers": "JS/MJS wrappers (hlk-loader, verify-integrity, hook bridge, cli-select)",
    "HLK/bin": "CLI lifecycle (install, update, pack, repack, status)",
    "HLK/security": "sanitizer (redact secrets) + vault-bridge",
    "HLK/git-tools": "git commit/push/pull/doctor/merge-ours/safe-sync",
    "HLK/config": "hlk.config.json + secrets.env.example (secrets thật gitignored)",
    "HLK/docs": "17 tài liệu HLK tiếng Việt",
    "HLK/prompts": "6 analysis/hardening prompts",
    "HLK/reports": "analysis reports + learnings",
    "HLK/skills": "hlk skills (git-tools, integrity-check, upstream-pull)",
    "HLK/loop": "hlk-loop.config.json + hlk-loop.mjs",
    "HLK/setup": "install scripts (sh/ps1/mjs)",
    "HLK/custom-hooks": "hook drop-in dirs",
    "HLK/upstream": "upstream pull mjs",
    "tests": "95 pytest files + conftest — coverage gate 80% (.devin/scripts + hooks)",
    "docs": "guides, plans, reports, research, templates",
    "docs/plans": "plan artifacts theo feature",
    "docs/reports": "quality/security reports",
    "docs/research": "research notes (orchestration, planning, QC)",
    "docs/templates": "PLAN_TEMPLATE.md + SDD_TEMPLATE.md",
    "tools": "PowerShell + Python utilities (verify, health-check, backup, deploy, ...)",
    ".github": "CI/CD + supply-chain",
    ".github/workflows": "37 workflows (ci, v3-ci, integration, verification, codeql, supply-chain, smoke tests)",
    "specs": "TLA+ formal specs (plan_orchestrator.tla, state_router.tla)",
    "sbom": "Software Bill of Materials (npm + python)",
}

# File root (key = tên file) — file quan trọng, Cline nên biết trước.
ROOT_NOTES = {
    "AGENTS.md": "ENTRY chính cho agent — Devin CLI config + skills + 3-Phase + guardrails + MCP + Khuym workflow",
    "CLAUDE.md": "Universal rules — security, code quality, file org, workflow, language policy",
    "opencode.json": "opencode config — skills paths + permissions (deny force-push/rm -rf/... )",
    "pyproject.toml": "Python metadata + deps (pydantic, filelock<3.13, cryptography) + coverage config",
    "pytest.ini": "pytest config — testpaths + coverage gate 80% + hypothesis",
    "package.json": "npm scripts — security:audit, setup:max-power, update:max-power",
    "REPOS.md": "Master reference list — repo tham khảo/deployed/vendored",
    "SECURITY.md": "Security policy",
    "devin-run.ps1": "Launcher Devin CLI (wrapper)",
    "devin-swe.ps1": "Launcher Devin SWE",
    "activate.ps1": "Activate environment",
    "loop": "Loop launcher (text)",
    "session": "Session token file (text)",
    "renovate.json": "Renovate dependency config",
    "requirements-lock.txt": "Python deps lock",
    ".gitignore": "Ignore rules — runtime dirs đều bị loại (phân biệt source vs runtime)",
    ".gitattributes": "Git attributes (line ending, diff)",
    ".ignore": "Ignore cho tool (học từ .gitignore)",
    "LICENSE": "MIT license",
    "activate.cmd": "Activate environment (Windows)",
    "devin-run.cmd": "Launcher Devin CLI (Windows)",
    "devin-swe.cmd": "Launcher Devin SWE (Windows)",
}


CANON_NOTES = {
    "CORE_CANON.md": "Rule gốc — source of truth tool-agnostic; mọi entry file sinh từ đây",
    "BOOT_PROTOCOL.md": "Startup sequence — 17 steps lazy-load; order bắt buộc",
    "REDLINES.md": "Hard stops — vi phạm = dừng, hỏi human",
    "MEMORY_PROTOCOL.md": "Three-layer memory + deep-memory (state trên disk, không trong context)",
    "LOOP_PROTOCOL.md": "Loop/goal primitives, stop conditions, idle-yank",
    "LOOP_GOAL_BASED.md": "Loop chế độ goal-based",
    "LOOP_PROACTIVE.md": "Loop chế độ proactive",
    "LOOP_TIME_BASED.md": "Loop chế độ time-based",
    "LOOP_TURN_BASED.md": "Loop chế độ turn-based",
    "VERIFICATION_PROTOCOL.md": "Maker≠checker, verification anchor tiers",
    "CAVEMAN_PROTOCOL.md": "Token compression style (~65% reduction)",
    "HARNESS_ENGINEERING.md": "Design principles cho agent-facing systems",
    "JUDGMENT_RUBRICS.md": "Externalized decision criteria",
    "HANDOFF_LETTER.md": "Letter cho session kế tiếp",
    "DAEMON_PROTOCOL.md": "Daemon mode runtime",
}

# Skill package hoặc flat file (key = tên trong .devin/skills/).
SKILL_NOTES = {
    "full-power": "3-Phase đầy đủ (Plan→Approve→Execute), max parallel, FORCE Plan bắt buộc",
    "plan": "Phase 1: Plan — auto orchestrate qua plan_orchestrator.py (Brainstorm→SDD→Approve→Plan→QC→Plan approval)",
    "lightning": "Executor SWE-1.7 Lightning (1000 tok/s)",
    "glm": "Executor GLM-5.2 High (free)",
    "kimi": "Executor Kimi K2.7 (free tier)",
    "adversarial-consensus": "6+ persona adversarial review (Saboteur, New Hire, Security Auditor, ...)",
    "aide-memory": "Persistent cross-session memory (MCP recall/remember/search)",
    "nuwa-skill": "Cognitive skill distillation — perspective skills (Munger/Feynman/Taleb) + Nuwa verify",
    "hlk-git-tools": "Git commit/push/doctor tools (via HLK)",
    "hlk-integrity-check": "Verify HLK layer integrity",
    "harness-upgrade": "Rà soát + nâng cấp workspace thành best harness (token-efficient)",
    "assets": "Slop patterns + vault assets",
    "domain-adapters": "Domain adapter templates",
    "update_from_repos": "Safe workspace update từ REPOS.md (detect upstream, cherry-pick, protect HLK/local)",
    "auditor.md": "Adversarial code review — tìm lỗ hổng security, giả định sai",
    "claim-grader.md": "Grade claim: [fact] / [inference] / [unverified] — chống hallucination",
    "comment_checker.md": "Detect AI-slop comments (filler, restating-the-obvious)",
    "context-compactor.md": "Compress context khi oversized — caveman 4 levels",
    "fable-judge.md": "Adversarial done-gate — verify tác phẩm done thật sự",
    "gap-scan.md": "Quét thiếu sót trước QC",
    "graph-verify.md": "Structural verify graph",
    "harness-sensor.md": "Sensor harness — output = fix instructions",
    "init_deep.md": "Init sâu project context",
    "loop-memory.md": "Loop memory sync",
    "memory-audit.md": "Audit memory + generate entry files",
    "slop-detector.md": "Detect AI filler/generic abstractions trong prose/docs/code",
    "systematic_debugging.md": "Debug methodology — reproduce → isolate → hypothesize → test → fix → verify",
    "tdd.md": "Test-Driven Development — failing test → implement → refactor",
    "user-preference.md": "Học + áp dụng user preferences (style, communication, workflow)",
    "using-skills.md": "Skill-first methodology — check skill trước khi act",
}

AGENT_NOTES = {
    "COMMANDER.md": "Orchestrator — phân tích ý định, dispatch, tích hợp, quyết định",
    "DISPATCH_TEMPLATES.md": "Template dispatch workers/subagents",
    "PERSONA_TEMPLATE.md": "Template tạo persona",
    "model_tiers.md": "Bảng phân cấp model + cost",
    "personas/architect.md": "Thiết kế SOLUTION_DESIGN.md (SDD)",
    "personas/code_reviewer.md": "Review code",
    "personas/git_workflow_master.md": "Git workflow best practices",
    "personas/new_hire.md": "Hỏi ngây thơ — bài kiểm tra onboarding",
    "personas/saboteur.md": "Chuyên đập giả định — tìm kẽ hở",
    "personas/security_auditor.md": "Audit security",
    "workers/SCOUT.md": "Scan/khảo sát — thu thập finding",
    "workers/BUILDER.md": "Build/implement",
    "workers/AUDITOR.md": "Audit đối kháng",
    "workers/VERIFIER.md": "Verify độc lập (maker≠checker)",
    "workers/MEMORY_KEEPER.md": "Ghi memory persistent",
    "glm-executor/AGENT.md": "Executor GLM-5.2 (free)",
    "kimi-executor/AGENT.md": "Executor Kimi K2.7 (free)",
    "lightning-executor/AGENT.md": "Executor SWE-1.7 Lightning",
}

HOOK_NOTES = {
    "pre_tool_use.py": "Guard thao tác nguy hiểm + enforce context compaction",
    "post_tool_use.py": "Log tool usage + detect context overload + micro-memory",
    "stop.py": "Clean exit khi session kết thúc",
    "session_start.py": "BOOT enforcement + HLK status check (U56/T2.8)",
    "session_end.py": "Cleanup + save memory khi session end (U70)",
    "user_prompt_submit.py": "Inject context vào user prompt (U70)",
    "plan_enforce.py": "BLOCK Write/Edit nếu chưa có approved plan (Devin CLI lifecycle)",
    "schema_gate.py": "Gate deterministic — kiểm tra mọi output agent",
    "coverage_enforce.py": "Theo dõi coverage matrix cho plan items",
    "drift_detect.py": "Phát hiện behavioral drift bằng JS divergence",
    "self_heal.py": "Tự chữa tri PostToolUse",
    "otel_instrument.py": "OpenTelemetry wrapper cho mọi hook/tool call",
    "observation_masking.py": "Filter tool outputs khỏi history sau khi dùng",
    "context_compaction.py": "Auto-compact session/loop state khi oversized",
    "compress_terminal_output.py": "Nén terminal noise để tiết kiệm token",
    "prompt_cache_metrics.py": "Track cache hit/miss cho stable prefixes",
    "ahd_session.py": "Shared session helpers (lib cho hook/script)",
}

# Scripts .devin/scripts/*.py — key = tên file.
SCRIPT_NOTES = {
    "plan_orchestrator.py": "ORCHESTRATOR CHÍNH — FSM auto plan/execute toàn harness (init/step/status)",
    "plan_dispatch.py": "Dispatch task theo file ownership (song song, ghi disjoint)",
    "build_workflow.py": "Build workflow DAG từ task list",
    "dag_compile.py": "Compile task list → DAG",
    "dag_executor.py": "Execute DAG (tuần tự)",
    "dag_executor_async.py": "Execute DAG (async, parallel)",
    "dyflow.py": "Dynamic Workflow — phát hiện dependency file → sinh DAG",
    "swarm_director.py": "Swarm director — điều phối swarm",
    "swarm_judge.py": "Swarm judge — chấm output swarm",
    "three_role.py": "Three-Role Orchestration (summarizer/main/corrector) cho model nhỏ",
    "tscg.py": "Tool-Schema Compression — nén schema trong budget token, giữ tool-call accuracy",
    "fsm_model_check.py": "Model check state machine",
    "state_router.py": "State router — định tuyến state theo event",
    "state_schema.py": "Schema state dùng chung",
    "migrate_config.py": "Migrate config giữa phiên bản",
    "migrate_state.py": "Migrate state giữa phiên bản",
    "checkpoint.py": "Checkpoint state để resume",
    "session_manager.py": "Quản lý session lifecycle",
    "memory_audit.py": "Audit memory + generate entry files (deploy contract)",
    "loop_memory_sync.py": "Sync loop memory giữa sessions",
    "cognitive_scaffold_memory.py": "Cognitive scaffold memory",
    "context_guard.py": "Guard context overflow",
    "context_projection.py": "Projection context cho subagent",
    "adaptive_compress.py": "Nén context adaptive",
    "approval_gate.py": "2 approval gates interactive (SDD + plan) — Ed25519 verify chữ ký reviewer",
    "plan_quality_check.py": "10-D quality check cho plan",
    "coverage_matrix.py": "Coverage matrix theo plan items",
    "llm_as_judge.py": "LLM-as-judge cho output",
    "fable_judge_compensation.py": "Fable judge + compensation",
    "best_of_n.py": "Best-of-N sampling (nhiều mẫu → chọn tốt nhất)",
    "self_consistency.py": "Self-consistency sampling",
    "cot_synthesis.py": "Chain-of-thought synthesis",
    "reflection_gate.py": "Reflection gate",
    "reward_shaping.py": "Reward shaping (ADOPS/LaRes/ARES) — phạt over-budget/security, detect reward hack",
    "qa_doc_audit.py": "Audit tài liệu QA",
    "abc_checklist.py": "ABC checklist verification (acceptance criteria)",
    "pre_task_audit.py": "Pre-task audit trước khi execute",
    "sbom_verify.py": "Verify SBOM",
    "nuwa_roi.py": "Nuwa ROI measurement (lợi ích Nuwa-audit)",
    "benchjack_redteam.py": "BenchJack red-team fixture feed (exploit mẫu deterministic)",
    "cost_dashboard.py": "Dashboard chi phí",
    "cost_ledger.py": "Ledger ghi chi phí",
    "cost_tracker.py": "Tracker chi phí theo session",
    "spc_monitor.py": "SPC (statistical process control) monitor",
    "hook_integrity.py": "Verify hook hashes/integrity",
    "path_zones.py": "Safe path zones — quy tắc đường dẫn được phép",
    "subagent_isolation.py": "Cô lập subagent (không cắn nhau, không role bleed)",
    "idempotency.py": "Idempotent ops — lock backend (filelock, fail-closed)",
    "artifact_registry.py": "Registry artifact (chữ ký, ownership)",
    "data_models.py": "Data models dùng chung",
    "event_bus.py": "Event bus publish/subscribe",
    "blackboard.py": "Bảng đen bộ nhớ dùng chung (hypotheses append-only, evidence single-writer)",
    "prompt_template.py": "Prompt template engine",
    "show_diff.py": "Show diff chuẩn hóa",
    "log_rotation.py": "Log rotation",
    "worktree.py": "Git worktree isolation cho task song song",
    "apply_ahd_patch.py": "Áp dụng AHD patch (normalize/rollback/protected verify)",
    "check_updates.py": "Kiểm tra update từ upstream repos",
    "merge_updates.py": "Merge an toàn 1 nguồn vendored skill từ REPOS_TRACKER",
    "update_common.py": "Update helpers dùng chung",
    "auto_model_router.py": "Routing model theo task type + cost",
    "agents/registry.py": "Registry agent lifecycle (owner/expiry/revocation)",
    "test_best_of_n.py": "Tự kiểm best_of_n",
    "test_self_consistency.py": "Tự kiểm self_consistency",
    "test_subagent_isolation.py": "Tự kiểm subagent_isolation",
}

SCRIPT_GROUPS = {
    "Orchestration & Plan": [
        "plan_orchestrator.py", "plan_dispatch.py", "build_workflow.py",
        "dag_compile.py", "dag_executor.py", "dag_executor_async.py",
        "dyflow.py", "swarm_director.py", "swarm_judge.py",
        "three_role.py", "tscg.py", "fsm_model_check.py",
    ],
    "State & Persistence": [
        "state_router.py", "state_schema.py", "migrate_config.py",
        "migrate_state.py", "checkpoint.py", "session_manager.py",
        "agents/registry.py", "artifact_registry.py",
    ],
    "Memory & Context": [
        "memory_audit.py", "loop_memory_sync.py", "cognitive_scaffold_memory.py",
        "context_guard.py", "context_projection.py", "adaptive_compress.py",
    ],
    "Quality & Verification": [
        "approval_gate.py", "plan_quality_check.py", "coverage_matrix.py",
        "llm_as_judge.py", "fable_judge_compensation.py", "best_of_n.py",
        "self_consistency.py", "cot_synthesis.py", "reflection_gate.py",
        "reward_shaping.py", "qa_doc_audit.py", "abc_checklist.py",
        "pre_task_audit.py", "sbom_verify.py", "nuwa_roi.py",
        "benchjack_redteam.py", "test_best_of_n.py", "test_self_consistency.py",
        "test_subagent_isolation.py",
    ],
    "Cost & Telemetry": [
        "cost_dashboard.py", "cost_ledger.py", "cost_tracker.py",
        "spc_monitor.py",
    ],
    "Security & Isolation": [
        "hook_integrity.py", "path_zones.py", "subagent_isolation.py",
        "idempotency.py",
    ],
    "Shared & Utilities": [
        "data_models.py", "event_bus.py", "blackboard.py",
        "prompt_template.py", "show_diff.py", "log_rotation.py",
        "worktree.py", "apply_ahd_patch.py", "check_updates.py",
        "merge_updates.py", "update_common.py", "auto_model_router.py",
    ],
}

# Subpackages trong .devin/scripts/ — key = 'pkg/file.py'.
SUBPACKAGE_NOTES = {
    "plan_fsm/__init__.py": "Plan FSM package — modular state machine",
    "plan_fsm/classifier.py": "Phân loại task tier (S/M/L/XL)",
    "plan_fsm/cli.py": "CLI plan_orchestrator: --init/--step/--status",
    "plan_fsm/constants.py": "Constants Plan FSM: state, action, giới hạn loop",
    "plan_fsm/missions.py": "Mission/persona generators cho SCOUT/reviewers/writer",
    "plan_fsm/state_machine.py": "State machine: next_action + process_step",
    "plan_fsm/state_machine_v2.py": "State machine v2 — graph-based (StateGraph)",
    "plan_fsm/storage.py": "Storage helpers: repo root, slugify, đọc/ghi state + plan",
    "runtime/__init__.py": "Runtime package — async execution, streaming, caching",
    "runtime/async_task_graph.py": "AsyncTaskGraph — DAG async execution",
    "runtime/backpressure.py": "BackpressureQueue — bounded queue",
    "runtime/cache_layer.py": "CacheLayer — semantic cache TTL + similarity",
    "runtime/cancellation.py": "CancellationToken — cooperative cancel",
    "runtime/llm_stream.py": "StreamAdapter — streaming thống nhất SWE-1.7/GLM/Kimi",
    "runtime/token_budget.py": "TokenBudget & CostOptimizer — quản lý budget + routing",
    "graph_engine/__init__.py": "Graph Engine package — dynamic workflow với StateGraph",
    "graph_engine/edges/base.py": "Base edge — cạnh nối giữa các node",
    "graph_engine/nodes/base.py": "Base node — đơn vị xử lý trong graph",
    "graph_engine/state_graph.py": "StateGraph — dynamic graph engine (LangGraph-compatible)",
    "graph_engine/checkpointer.py": "Checkpointer cho graph persistence",
    "state_store/interface.py": "StateStore abstract interface",
    "state_store/__init__.py": "StateStore package — pluggable state persistence",
    "state_store/backends/__init__.py": "Backends registry (file + redis)",
    "state_store/file_backend.py": "FileBackend — local state (JSONL + SQLite index)",
    "state_store/backends/redis_backend.py": "RedisBackend — distributed state",
    "agents/registry.py": "Registry agent lifecycle (owner/expiry/revocation)",
    "state_machine_v2/event_store.py": "Event store cho state machine v2",
    "adapters/__init__.py": "Adapters package — dual-write migration adapters",
    "adapters/migration_coordinator.py": "MigrationCoordinator — saga orchestrator dual-write",
    "adapters/plan_state_adapter.py": "PlanStateAdapter — dual-write plan state",
    "adapters/session_state_adapter.py": "SessionStateAdapter — dual-write session state",
    "adapters/execution_state_adapter.py": "ExecutionStateAdapter — dual-write execution state",
}

OPCODE_NOTES = {
    "README.md": "Mô tả lớp wrapper opencode — cách nạp skills/agents/hooks, an toàn fail-open",
    "config.json": "Config opencode (theo schema opencode.ai)",
    "plugin/harness.ts": "Hook bridge — chạy .devin/hooks/*.py qua subprocess; TẮT mặc định (chỉ bật khi OPENCODE_HARNESS_HOOKS=1)",
    "command/harness-upgrade.md": "Launcher /harness-upgrade",
    "agents/harness-orchestrator.md": "Agent orchestrator harness",
    "agents/harness-executor-glm.md": "Executor GLM",
    "agents/harness-executor-kimi.md": "Executor Kimi",
    "agents/harness-executor-lightning.md": "Executor Lightning",
    "agents/harness-subagent.md": "Subagent harness",
    "agents/harness-verifier.md": "Verifier harness",
}

HLK_NOTES = {
    "README.md": "Tổng quan HLK — security layer, setup max-power",
    "config/hlk.config.json": "Bật/tắt HLK, security rules, telemetry overrides",
    "wrappers/hlk-loader.js": "Interceptor — bind sanitizer, telemetry blocker, vault",
    "wrappers/hlk-verify-integrity.js": "Post-update HLK integrity checker",
    "security/sanitizer.js": "Redact API keys/tokens/passwords",
    "security/vault-bridge.js": "Quản lý secrets qua env vars / local .env",
    "git-tools/hlk-git-commit.mjs": "Git commit (safe)",
    "git-tools/hlk-git-push.mjs": "Git push (safe)",
    "git-tools/hlk-git-doctor.mjs": "Git doctor",
    "git-tools/hlk-merge-ours.mjs": "Merge ours cho upstream update",
    "git-tools/hlk-check-merge-ours.mjs": "Check trạng thái merge-ours",
    "git-tools/hlk-git-safe-sync.mjs": "Safe sync upstream",
    "loop/hlk-loop.mjs": "HLK continuous loop",
    "skills/hlk-git-tools/SKILL.md": "Skill git tools (HLK)",
    "skills/hlk-integrity-check/SKILL.md": "Skill integrity check (HLK)",
}

DOC_NOTES = {
    "AGENTS_full_reference.md": "Full reference AHD (nạp on-demand)",
    "BOOT_PROTOCOL_full.md": "Full BOOT protocol",
    "REDLINES_full.md": "Full red lines",
    "USAGE_GUIDE.md": "Hướng dẫn dùng tất cả skills/agents/flows",
    "CONTINUOUS_LOOP_GUIDE.md": "Hướng dẫn chạy loop liên tục",
    "PLAN_ORCHESTRATOR_GUIDE.md": "Hướng dẫn kỹ thuật plan orchestrator",
    "REDTEAM_AUDIT.md": "Red-team audit (lịch sử)",
}

TOOL_NOTES = {
    "verify-workspace.ps1": "Verify workspace integrity",
    "gen_source_map.py": "Python — sinh .clinerules/00-source-map.md (source map cho Cline)",
    "source_map_data.py": "Python — data module mô tả cho gen_source_map.py",
            "check_governance.py": "Python — lint Workspace Governance (file rác, layout, plan↔act; exit 0/1/2)",
    "cline-toggle-rules.sh": "POSIX shell — bật/tắt/status/toggle .clinerules/ (Cline rules layer)",
    "cline-toggle-rules.ps1": "PowerShell — bản Windows của cline-toggle-rules.sh",
    "health-check.ps1": "Kiểm tra sức khỏe hệ thống",
    "backup-workspace.ps1": "Backup workspace",
    "restore-workspace.ps1": "Restore workspace state",
    "deploy-template.ps1": "Deploy template",
    "rollback-deploy.ps1": "Rollback deploy",
    "package-template.ps1": "Package template",
    "init-new-project.ps1": "Khởi tạo project mới",
    "merge-config.ps1": "Merge config",
    "clean-runtime.ps1": "Dọn runtime artifacts",
    "cleanup-orphan-sessions.ps1": "Dọn session mồ côi",
    "risk-contract-check.ps1": "Check risk contract",
    "cross_platform.py": "Python — xử lý chéo platform",
    "import_smoke_test.py": "Python — smoke test import",
    "aide-memory-daemon.ps1": "Daemon aide-memory",
    "FULL_POWER_PROMPT.md": "Prompt full power",
    "README.md": "README tools",
}

GITHUB_NOTES = {
    "workflows/ci.yml": "CI chính",
    "workflows/v3-ci.yml": "CI v3",
    "workflows/integration-tests.yml": "Integration tests",
    "workflows/verification-pipeline.yml": "Verification pipeline",
    "workflows/codeql.yml": "CodeQL security scan",
    "workflows/supply-chain.yml": "Supply-chain audit",
    "workflows/metaharness-ci.yml": "Meta-harness CI",
    "workflows/ruflo-agent-smoke.yml": "Smoke test ruflo agent",
    "workflows/rollback-manager.yml": "Rollback manager",
    "workflows/clone-tracker.yml": "Clone tracker",
    "workflows/cost-tracker-smoke.yml": "Smoke test cost tracker",
    "workflows/status-badges.yml": "Status badges",
    "CODEOWNERS": "Owners per path",
    "dependabot.yml": "Dependabot config",
}

DEVIN_ROOT_NOTES = {
    "AGENTS.md": "AHD entry — summary; nạp canon on-demand theo BOOT_PROTOCOL",
    "AGENTS_full.md": "186KB full body — KHÔNG auto-load (đọc on-demand khi cần)",
    "config.json": "Devin CLI config — permissions (allow/deny/ask), hooks, model routing",
    "config.local.json": "Config local (gitignored)",
    "config.minimal.json": "Config tối thiểu",
    "mcp_config.json": "MCP servers (aide-memory, spark-memory, deepwiki, devin)",
    "memory_config.json": "Memory config",
    "tool_registry.json": "Tool registry — L0-L4 permission taxonomy",
    "hook_hashes.json": "Hash baseline hooks (integrity)",
    "risk_contract.json": "Risk contract",
    "loop_state.md": "Registry loop state — đọc ở boot",
    "loop_state": "Loop state directory entry (runtime)",
    "ATTRIBUTION.md": "Ghi công các nguồn/distilled skills",
    "loop_state_archive.md": "Archive loop state",
    "schemas/hook_io_schema_v1.json": "JSON schema hook IO",
}

